name: Update Cloudflare KV

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  update-kv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update and Install Wrangler
        run: npm uninstall -g @cloudflare/wrangler && npm install -g wrangler

      - name: Update KV Store with Markdown Files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' | while read filename; do
            key=$(basename "$filename" .md)
            wrangler kv:key put --namespace-id="${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}" "$key" --path="$filename"
          done
        env:
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
