name: Update Cloudflare KV

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  update-kv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update and Install Wrangler
        run: npm uninstall -g @cloudflare/wrangler && npm install -g wrangler

      - name: Authenticate Wrangler
        run: wrangler whoami
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Update KV Store with Markdown Files
        run: |
          git diff --name-only HEAD^ HEAD | grep '\.md$' | while read filename; do
            key=$(basename "$filename" .md)
            value=$(cat "$filename")
            wrangler kv:key put --binding=YOUR_KV_BINDING "$key" "$value"
          done
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
