name: Update Cloudflare KV

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  update-kv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g @cloudflare/wrangler

      - name: Authenticate Wrangler
        run: wrangler config
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Update KV Store with Markdown Files
        run: |
          git diff --name-only HEAD^ HEAD | grep '\.md$' | while read filename; do
            key=$(basename "$filename" .md)
            value=$(cat "$filename")
            wrangler kv:key put --binding=BLOG_CONTENTS "$key" "$value"
          done
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
